baseURL = 'http://example.org/'
languageCode = 'ko'
title = 'RTOS Lab'
theme = 'hugo-book'

staticDir = 'static'

# Book configuration
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

[params]
  BookSection = 'docs'
  BookSerch=true
  BookLogo = 'img/logo.png'
  BookMenuBundle = '/menu'
  BookToC = true

[module]
[[module.mounts]]
  source = 'static/img/Photos/'
  target = 'static/img/Photos/'